# Generated by Django 5.0.14 on 2025-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('CompanyID', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('CompanyName', models.CharField(max_length=25)),
            ],
        ),
    ]
